### ISSUE TITLE
Allow renaming of DB Instance via `DBInstanceIdentifier` without replacement update

### ISSUE THREAD

**Issue by amedeshm** [aws-cloudformation/cloudformation-coverage-roadmap#1043]
### Name of the resource

AWS::RDS::DBInstance

### Description

Currently is is possible to rename a RDS DB Instance by specifying the `NewDBInstanceIdentifier` property in the `ModifyDBInstance` API call. This can be done via the AWS CLI and the Console as well without the RDS DB Instance being replaced.

In CloudFormation, the functionality of `DBInstanceIdentifier` property should be updated to leverage the `NewDBInstanceIdentifier` property in the `ModifyDBInstance` API call to allow renaming the resource without replacement update.

**Comment by miiichael** [comment]
So the problem is that RDS Instances (and Clusters, and, I assume, other resources) don't actually have an immutable primary identifier?

But if one was added then Cloudformation could eventually use _that_ instead of the not-actually-immutable identifier, and the world would be a nicer place? The instance identifier (and the endpoint hostname) would then become freely modifiable via cloudformation, like it is via the console today.

Do I have that about right? 😅
