### ISSUE TITLE
AWS::AuditManager::Assessment Status

### ISSUE THREAD

**Issue by rajeshgovada** [aws-cloudformation/cloudformation-coverage-roadmap#1149]
### Name of the resource

AWS::AuditManager::Assessment

### Issue Description

The property **Status** is not being honored for the given value in the CloudFormation template for the resource AWS::AuditManager::Assessment, the Assessment is always being created with the state as Active, disregarding the value provided to the Status property, ACTIVE or INACTIVE.

Link to the reference documentation of the property in discussion: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-auditmanager-assessment.html#cfn-auditmanager-assessment-status

### Expected Behavior

Assessment status should be Active when the property Status is given as ACTIVE and should be Inactive when the property Status is given as INACTIVE.

### Observed Behavior

Assessment status is always created with the state as Active, even if the property value for Status is provided as INACTIVE

### Test Cases

**Test template**: [https://github.com/doctorqp/cloudformationbug/blob/main/auditmanagertest.yml](url)

Give destination S3 bucket for assessment report
Give IAM Role Arn to grant permissions to

Test case1: Select Assessment Status as ACTIVE and the created assessment should be active state
Test case2: Select Assessment Status as INACTIVE and the created assessment should be inactive state

**Comment by poonamverma-git** [comment]
Thanks for finding this, @rajeshgovada. This is not a bug, although the documentation should be more explanatory.

The behavior that you observed is working correctly by design. There are 2 possible status values for an assessment: ACTIVE or INACTIVE. By default, the initial status for a new assessment is always ACTIVE. This means that even if you specify the status as INACTIVE when you create the assessment, Audit Manager will override the initial status to ACTIVE. After the assessment is created, you can then change the status value to INACTIVE at any time.

I apologize if this caused you any frustration in using or learning about Audit Manager. We have updated the documentation to clarify the behavior of the Status property. Thanks again for taking the time to leave this feedback so that we could improve our documentation.
