### ISSUE TITLE
resolve:secretsmanager cannot find secrets with hyphen in name

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/cloudformation-coverage-roadmap#1187]
### Name of the resource

AWS::SecretsManager::Secret

### Issue Description

_resolve:secretsmanager_ seems to not be able to fetch secrets with names that include hyphens.

### Expected Behavior

_resolve:secretsmanager_ **SHOULD** be able to fetch secrets with names that include hyphens.

### Observed Behavior

_resolve:secretsmanager_  is **NOT** able to fetch secrets with names that include hyphens.

### Test Cases

Using the following template, (remember to replace AccountId and Region), and having created the following two secrets in Secrets Manager:

1. sandbox/pass
2. my-super-secret

`aws cloudformation deploy --stack-name lab --template-file template.yaml --capabilities CAPABILITY_IAM --parameter-overrides SecretNameParam='sandbox/pass'`

This command works just fine.

`aws cloudformation deploy --stack-name lab --template-file template.yaml --capabilities CAPABILITY_IAM --parameter-overrides SecretNameParam='my-super-secret'`

Whilst this one fails with...

>   Secrets Manager can't find the specified secret. (Service: AWSSecretsManager; Status Code: 400; Error Code: ResourceNotFoundException;

```
Parameters:
  SecretNameParam:
    Type: String
    Description: Name to fetch from Secrets Manager.

Resources:
  LambdaFunctionServiceRoleC555A460:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - Fn::Join:
            - ''
            - - 'arn:'
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LabStack/LambdaFunction/ServiceRole/Resource
  LambdaFunctionBF21E41F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Sub |
          import json
          def handler(event, context):
            print('helloworld')
      Role:
        Fn::GetAtt:
          - LambdaFunctionServiceRoleC555A460
          - Arn
      Environment:
        Variables:
          username:
            Fn::Join:
              - ''
              - - '{{resolve:secretsmanager:arn:'
                - Ref: AWS::Partition
                - ':secretsmanager:eu-west-1:0000000000:secret:'
                - Ref: SecretNameParam
                - :SecretString:username::}}
          password:
            Fn::Join:
              - ''
              - - '{{resolve:secretsmanager:arn:'
                - Ref: AWS::Partition
                - ':secretsmanager:eu-west-1:0000000000:secret:'
                - Ref: SecretNameParam
                - :SecretString:password::}}
      Handler: index.handler
      Runtime: python3.9
    DependsOn:
      - LambdaFunctionServiceRoleC555A460


Outputs:
  UsernameOutput:
    Description: Username imported from Secrets Manager.
    Value:
      Fn::Join:
        - ''
        - - '{{resolve:secretsmanager:arn:'
          - Ref: AWS::Partition
          - ':secretsmanager:eu-west-1:0000000000:secret:'
          - Ref: SecretNameParam
          - :SecretString:username::}}
  PasswordOutput:
    Description: Password imported from Secrets Manager.
    Value:
      Fn::Join:
        - ''
        - - '{{resolve:secretsmanager:arn:'
          - Ref: AWS::Partition
          - ':secretsmanager:eu-west-1:0000000000:secret:'
          - Ref: SecretNameParam
          - :SecretString:password::}}

```

**Comment by JoeJesse** [comment]
Hi [greg5123334](https://github.com/greg5123334),

The issue is actually not with the use of hyphens in the secret name itself, but rather a combination of the following:

- The template above is constructing a partial secret ARN as the value for the secret-id segment in the [Secrets Manager dynamic reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-secretsmanager)
- The friendly secret name used ('my-super-secret') ends with a hyphen followed by six characters, which follows the same pattern AWS Secrets Manager uses to suffix secret ARNs. As a result, this creates ambiguity in the dynamic reference [GetSecretValue](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html#SecretsManager-GetSecretValue-request-SecretId) call

This is a special case and is covered in the [Troubleshooting](https://docs.aws.amazon.com/secretsmanager/latest/userguide/troubleshoot.html#ARN_secretnamehyphen) section of our public documentation.

That being said, I would recommend using one of following two approaches:
1. If the secrets you are making dynamic references to are in the same account/region that you are creating the above stack in, I would recommend using the friendly secret name to populate the value for the secret-id segment
2. Else, pass in the **full** secret ARN to the `SecretNameParam` stack parameter.
