### ISSUE TITLE
Add support for EFS CreateReplicationConfiguration

### ISSUE THREAD

**Issue by corymhall** [aws-cloudformation/cloudformation-coverage-roadmap#1270]
### Name of the resource

AWS::EFS::FileSystem

### Description

In January 2022 EFS released support for replication. https://aws.amazon.com/blogs/aws/new-replication-for-amazon-elastic-file-system-efs/

Currently there is no way to configure this in CloudFormation. Not sure if it makes more sense to add it to the `AWS::EFS::FileSystem` resource or to create a new resource `AWS::EFS::FileSystemReplication`?

**Comment by SebastianNichtern** [comment]
Any updates on this?

**Comment by dale-c-anderson** [comment]
One man's opinion: Since replication is currently added with cli after the the efs instance exists, it would make more sense (and be simpler) for the CF resource to also work that way. 

It's no added complication to reference an existing EFS resource, whether it was created manually, or whether it was created 2 seconds before in another CF stack.

The benefit of it being separate is that you don't end up with a chicken/egg scenario where you want to add replication to an existing resource, but you can't because the EFS you want to add it to already exists.

**Comment by rdbatch02** [comment]
It looks like this was now added to CloudFormation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-replicationconfiguration
