### ISSUE TITLE
AWS::Cloud9::EnvironmentEC2

### ISSUE THREAD

**Issue by shivlaks** [aws-cloudformation/cloudformation-coverage-roadmap#129]
### Title
AWS::Cloud9::EnvironmentEC2

### Scope of request
AWS::Cloud9::EnvironmentEC2 supports Amazon Linux environments but not `Ubuntu`. Support for [Ubuntu development environments in Cloud9](https://aws.amazon.com/about-aws/whats-new/2019/04/aws-cloud9-announces-support-for-ubuntu-development-environments/) was launched on 04/02/2019

### Expected Behavior
  AWS::Cloud9::EnvironmentEC2 resource should support creation of Ubuntu EC2 development environments

### Links
* [Cloud9 documentation for environment creation](https://docs.aws.amazon.com/cloud9/latest/user-guide/create-environment-main.html)

relevant snippet:
```
For Platform, choose the type of Amazon EC2 instance that AWS Cloud9 will create and then connect to this environment: Amazon Linux or Ubuntu.
```

* [Cloud9 Ubuntu launch announcement](https://aws.amazon.com/about-aws/whats-new/2019/04/aws-cloud9-announces-support-for-ubuntu-development-environments/) 

## Category
Developer Tools

## Additional Context
* Related issue raised in AWS CDK repo aws/aws-cdk#3678

**Comment by omenking** [comment]
I use Cloud9 to teach large groups of people AWS. What I want to do is trigger a lambda function to deploy a CloudFormation stack onto multiple AWS accounts that will provision Cloud9.

The obstacle we face is the fact that Amazon Linux 1 is using init.d and Amazon Linux 2 uses systemsd. The reason this is so important is that you can't install modern libraries such as Postgres 11 client on Amazon Linux 1 since it relies on systemd.

If I could launch Amazon Linux 2 or Ubuntu that would mitigate that issue.

**Comment by barry963** [comment]
Hi, this is a late reply, Cloud9 supports both AL2 and Ubuntu since end of 2019. Please check the doc https://docs.aws.amazon.com/cloud9/latest/user-guide/create-environment-main.html
