### ISSUE TITLE
AWS::SSO::PermissionSet InlinePolicy length limit is 1024 instead of 10240

### ISSUE THREAD

**Issue by sam9191** [aws-cloudformation/cloudformation-coverage-roadmap#1294]
### Name of the resource

AWS::SSO::PermissionSet

### Issue Description

On the AWS CloudFormation console, when I try to create a stack, containing a `AWS::SSO::PermissionSet` with an `InlinePolicy` I get the following error:
```
1 validation error detected: Value 'Invalid PermissionsPolicy Document
(Service: SsoAdmin, Status Code: 400, Request ID: XXX)' at 'statusMessage' failed to satisfy constraint: Member must have length less than or equal to 1024
```
My `InlinePolicy` is 1321 character long.

### Expected Behavior

To successfully create the `AWS::SSO::PermissionSet` as the `InlinePolicy` length limit should be 10240 characters. Please see the docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html#cfn-sso-permissionset-inlinepolicy 

### Observed Behavior

I get a validation error

### Test Cases

You can recreate the error by trying to create a CloudFormation stack on AWS console, containing a `AWS::SSO::PermissionSet` with an `InlinePolicy` of 1321 characters (excluding any spaces, tabs) or more.

**Comment by hopkinsnji** [comment]
We have successfully created permission sets with inline policies longer than 1024. We saw a similar error message referred to in this issue and opened a support ticket with AWS. It turns out, there was an error with the permissions set, however, the error message contains the entire permission set, of which the permission set is longer than 1024 but the error message can be max 1024. So looking closer at the error message:

'statusMessage' failed to satisfy constraint: Member must have length less than or equal to 1024

The status message failed to satisfy the constraint, so you can't see the error in the inline policy. What needs to happen to solve this is to truncate the inline policy in the error message to maybe the fist and last 100 characters.

**Comment by sam9191** [comment]
@hopkinsnji I think you're right. I just realised my inline policy was invalid. So as you said, the error message should be fixed to not confuse people!

**Comment by iainelder** [comment]
@hopkinsnji , your message gives hope. I'll contact AWS Support for more help.

My customer just got the same error today. The `UPDATE_FAILED` event has a ResourceStatusReason like this:

`1 validation error detected: Value 'Invalid PermissionsPolicy Document {...}. (Service: SsoAdmin, Status Code: 400, Request ID: ...)' at 'statusMessage' failed to satisfy constraint: Member must have length less than or equal to 1024`

The policy text in the full error message has 1858 characters.

What shipped to fix this? I think it needs to be reopened.
