### ISSUE TITLE
 Support for Import of AWS::Cognito::Pool Resource

### ISSUE THREAD

**Issue by cmogeni** [aws-cloudformation/cloudformation-coverage-roadmap#1485]
### Name of the resource

AWS::Cognito::UserPool

### Description

CloudFormation currently doesn't support import resource feature for the IAM Managed policy resource - AWS::Cognito::Pool.

Requesting to add resource type AWS::Cognito::Pool to support import operation.

**Comment by aiden-sobey** [comment]
Critical, would love to see this get added in.

**Comment by mousedownmike** [comment]
Not sure if it helps with spec'ing the implementation here but my use case is:

* I have a Cognito User Pool that was created with Terraform ~ 3 years ago.
* I have Lambda functions to handle messaging and JWT token enrichment defined in a SAM template.
* I would :heart: to move the User Pool to that same SAM template where it belongs so I can more easily reference the functions.

I'm at the point now where I have to manually update the Lambda function ARNs because their names are uniquely generated by the SAM template.  It's not a huge effort but it's a manual effort I would like to stop doing.

**Comment by jk2l** [comment]
I have one environment where a developer mistakenly attempt to delete the child stack containing the UserPool within a nested stack. fortunately because there are ExportValue dependency the deletion failed (It failed at UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS stage). but now i have the resource no longer managed by CloudFormation and i cannot import it back

**Comment by maxfielb** [comment]
This feature is now supported https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by AMZ-brandon** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

The following resources have been added to resources that support import:
AWS::Cognito::LogDeliveryConfiguration
AWS::Cognito::UserPool
AWS::Cognito::UserPoolClient
AWS::Cognito::UserPoolGroup
AWS::Cognito::UserPoolUser 
AWS::Cognito::UserPoolUserToGroupAttachment

The following resources have been added to resources that support drift detection:
AWS::Cognito::UserPoolClient
AWS::Cognito::UserPoolGroup
