### ISSUE TITLE
Add tag support to CloudWatch alarms

### ISSUE THREAD

**Issue by Gtofig** [aws-cloudformation/cloudformation-coverage-roadmap#1490]
### Name of the resource

AWS::CloudWatch::Alarm

### Description

CloudWatch alarms support tags, but this is not currently supported by CloudFormation. Please allow specifying tags directly at CloudWatch alarm resource level. 

Among other benefits, this would allow CDK users to apply tags universally via aspects, for example.

**Comment by rgoltz** [comment]
@Gtofig - This is a duplicate of https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/64 (as you see, there are already 170+ upvotes and with number #64 it's an older issue). May you check the details of this issue/comments (there is also a bloody CDK-based workaround with one tag per sec pattern) and add your upvote/notes there + close your issue here?

**Comment by Gtofig** [comment]
Closing, as it's a duplicate of https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/64

**Comment by rgoltz** [comment]
@Gtofig - You should take a new look at:
* https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/64#issuecomment-2033575776
* https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/64#issuecomment-2033623267

:-)
