### ISSUE TITLE
Managing Maintenance windows via CloudFormation; AWS::MediaLive::Channel

### ISSUE THREAD

**Issue by SuryaTeja18** [aws-cloudformation/cloudformation-coverage-roadmap#1561]
### Name of the resource

AWS::MediaLive::Channel

### Description

MaintenanceWindow property is not available via CloudFormation for the resource type AWS::MediaLive::Channel. This can hamper customers' ability to easily stand up new video services and customers can make use of this property very effectively as it could greatly help their decision to launch the services.

Ref.: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-medialive-channel.html

**Comment by ghhegnel** [comment]
Greetings,

We have enabled customers to provide a maintenance configuration for their MediaLive Channel using CloudFormation. In order to take advantage of this feature, customers will need to provide MaintenanceCreateSettings:
-  ([https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-medialive-channel.html#cfn-medialive-channel-maintenance](url)) 

These settings should be included under the Maintenance property found when creating a MediaLive Channel: 
- ([https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-medialive-channel.html#cfn-medialive-channel-maintenance](url))
