### ISSUE TITLE
(AWS::ApiGateway::Account) False-positive drift detection for CloudWatchRoleArn property

### ISSUE THREAD

**Issue by oceanofmaya** [aws-cloudformation/cloudformation-coverage-roadmap#1571]
### Name of the resource

AWS::ApiGateway::Account

### Issue Description

Stack drift detection on a previously existing stack is informing that AWS::ApiGateway::Account has drifted and when the results are viewed shows that `CloudWatchRoleArn` property has changed and it shows the actual as a value of `CloudWatchRoleArn` whatever new stack was deployed in the account. Interestingly when I run the drift detection for other stacks that have an ApiGateway, I see the same thing.

### Expected Behavior

Accurate drift detection results

### Observed Behavior

Inaccurate drift detection results.

### Test Cases

I use CDK to create a rest API. Below is a simplified example and it creates a CloudWatchArn when deployed. When I do a drift detection in another stack that was already in the account that had a different Api Gateway, it shows that the CloudWatchArn has drifted and points to the CloudWatchArn that was created by the newly deployed stack even though the template in the existing stack does not show such change.

```
const restApi = new RestApi('SomethingServiceGateway', {
      restApiName: 'something-gateway',
      deployOptions: {
        stageName: development,
      },
    });
```

**Comment by martzcodes** [comment]
I could see this happening with the RestApi option `cloudWatchRole: true` which ends up creating a Role and assigning ALL CloudWatchArn's to that stack's role.  In new CDK projects it defaults to false since `"@aws-cdk/aws-apigateway:disableCloudWatchRole": true,` is the in default cdk.json file

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.RestApi.html#cloudwatchrole

I have no idea why all API Gateways share a single role for CloudWatch, but technically that would be drift.

I think the real fix here would be for the API Gateway team to enable API-ownership of their own CloudWatch role.

**Comment by oceanofmaya** [comment]
@martzcodes you are right. I was able to find in the console when I navigated to `Settings` under `ApiGateway` for that Api Gateway I do see that the the CloudWatchRoleArn has changed.

Gah! Found it in the docs https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-apigateway/README.md

This means I have to create a single one somewhere for the account and have this as false everywhere.

Looks like it was added to CDK version https://github.com/aws/aws-cdk/releases/tag/v2.38.0 which contains the feature flag https://github.com/aws/aws-cdk/issues/2154 6
