### ISSUE TITLE
Aurora serverless v2, i/o-optimized  

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-cloudformation/cloudformation-coverage-roadmap#1691]
### Name of the resource

AWS::RDS::DBCluster

### Description

AWS recently added new feature, not sure if this is already in CF

<img width="743" alt="image" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/62673610/07d6f92f-6794-4f05-a859-f7edf73863c4">

**Comment by osdrv** [comment]
The io-optimized storage feature is globally available now. Though, there is a limitation @masteinhauser mentioned: a 30-day cool down period between storage type flips. The limitation is there by design. It was mentioned in the public release notes https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-aurora-i-o-optimized/.
> You can switch existing database clusters to Aurora I/O-Optimized once every 30 days and switch back to Aurora Standard at any time.

Hope this makes sense. Please give us a heads up if any other questions remain.

**Comment by osdrv** [comment]
@masteinhauser I really appreciate the clarification. I didn't get it initially that there is no change to the storage type. This one is on us. We will update this ticket once it is fixed. Thanks again.

**Comment by hibhag** [comment]
The Aurora IO optimized feature support has been rolled out in May 2023.

**Comment by masteinhauser** [comment]
Hello @hibhag, unfortunately while your statement is true for when the feature was released my bug reported is **still broken** based on re-testing the scenario that I described above just now. CloudFormation updates **are not possible** on an RDS cluster with a recently changed Storage Type. It is _very likely_ we will need to abandon use of I/O Optimized Storage because **CloudFormation support does not function!**

Please do not close bugs without test case verification.

**Comment by masteinhauser** [comment]
I am attaching a screenshot of my testing right now to try and further convince @osdrv and @hibhag this is still broken **and warn other AWS CloudFormation customers**

![Screenshot 2023-06-20 at 08 16 08](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/592187/6b933fb7-10b1-475b-ba98-d1c5f8a8f73e)

**Comment by hibhag** [comment]
@masteinhauser Got it, we will take a look for this specific scenario. Thanks for quick testing.

**Comment by danielxoi** [comment]
Hello! @hibhag will this change to open status as it's looked at?

**Comment by mjuszczak** [comment]
@osdrv and @hibhag, also curious as to whether this can be re-opened due to the outstanding bug?

**Comment by alexbarnes** [comment]
We are also seeing this same issue. Is there a plan to reopen this ticket to address the shortcomings of the implementation of this new feature?

**Comment by taxbit-xinghai** [comment]
we are also seeing the same issue when we did not even change the storage type

**Comment by danielxoi** [comment]
@hibhag any word if this will be re-opened?

**Comment by khebul** [comment]
@danielxoi I believe the issue is resolved now, and no-op changes to aurora IO optimized storage time no longer trigger mandatory cool down period
