### ISSUE TITLE
CloudFormation実行時に自動生成される「cf-templates-xxxxxxxxx」というS3バケットの生成抑止のお願い

### ISSUE THREAD

**Issue by m24-ito** [aws-cloudformation/cloudformation-coverage-roadmap#1748]
### Name of the resource

AWS::CloudFormation::Stack

### Description

CloudFormationのスタック実行すると、S3に「cf-templates-xxxxxxxxx」というバケットが自動生成されます。
これはCloudFormationの実行時に一時的に利用したS3バケットだと思いますが、
我々のユーザー側では不要なS3バケットになりますので、当該S3バケットが自動生成されないように改善をお願いします。

**Comment by Risae** [comment]
Hi, this only happens when you use `Upload a template file` to deploy a CloudFormation Stack:

![Screenshot 2023-07-17 094035](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/37260321/e67170fc-0cef-45e4-ac47-5789c01dcfd2)

As far as i know, CloudFormation needs a storage location to upload the Template to (in order to deploy it). To "prevent" CloudFormation from creating a S3 Bucket you have to create your own Bucket and upload the Template there, copying the S3 file url into the CloudFormation GUI.

I personally doubt that the CloudFormation devs will change this workflow any time soon though.

**Comment by TheDanBlanco** [comment]
yes, as described above creating the bucket for you is done for convenience. if you'd like to avoid the creation of this bucket, we recommend you provide your own url.
