### ISSUE TITLE
SageMaker Studio domain user fail to delete because of running apps

### ISSUE THREAD

**Issue by mlnrt** [aws-cloudformation/cloudformation-coverage-roadmap#1754]
### Name of the resource

AWS::SageMaker::UserProfile

### Resource Name

No response

### Issue Description

In SageMaker Studio domain, when user connects to notebooks environment, it spins-up new compute resource applications hosting the notebooks.
These apps created outside IaC must be deleted first, in order to delete the SageMaker Studio domain user created by CDK/CloudFormation.
Using a CustomResource to do that does not work because deleting an app can take up to 20 minutes so it is too long for a simple Lambda Function based Custom Resource.
WaitCondition do not work either since they do not work with delete.

### Expected Behavior

All the apps of a SageMaker Studio domain user are deleted automatically when deleting a user.

### Observed Behavior

When deleting the CloudFormation stack it will fail to delete the SageMaker Studio domain user because there are still apps running

### Test Cases

1. Create a SageMaker Studio Domain and User using CloudFormation
2. Start a Jupyter application for that user and run a Jupyter notebook
3. Exit the notebook
4. Delete the Stack
5. The stack deletion will fail when deleting the user because their are apps running.

### Other Details

No response

**Comment by durgasury** [comment]
Hi @minrt, thank you for bringing this to our attention. The current expected behavior is that all running apps for a user has to be deleted to delete the user profile. This avoids accidental deleting of user profiles who might have running apps (i.e., actively using Studio). 

The custom Lambda function can be used to call DeleteApp on all the user profile's apps, but I'm curious about apps taking up to 20 minutes to delete (it should take <5 minutes, a couple of minutes on average). 

We will take this up as a feature request, to allow force delete of users and apps.

**Comment by ashivadi** [comment]
Same thing happens for AWS::SageMaker::Space. CFN needs to provide support for deleting the apps.
