### ISSUE TITLE
AWS::OpenSearchService::Domain EncryptionAtRestOptions - Implement a AWS Managed Key Option

### ISSUE THREAD

**Issue by Ruben-Sh** [aws-cloudformation/cloudformation-coverage-roadmap#1799]
### Name of the resource

AWS::OpenSearchService::Domain

### Resource name

AWS::OpenSearchService::Domain EncryptionAtRestOptions

### Description

When creating a Open Search Service Domain and configuring fine grain access control encryption at rest is required. 

If the AWS console used to create the domain when encryption of data at rest is enabled the option is provided to use a AWS managed key or customer managed key. 

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/72896766/06dd85a0-010c-491d-9c13-5b3eabe94bfb)

When using CloudFormation AWS::OpenSearchService::Domain EncryptionAtRestOptions Enabled set to true a KMS key ID is required. The option for OpenSearch to create a AWS managed key is not available. Please see [1].

To reduce KMS key management overhead can the AWS::OpenSearchService::Domain EncryptionAtRestOptions be enhanced allowing the OpenSearchService to create a AWS managed key rather than require a customer managed key please.

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-encryptionatrestoptions.html#cfn-opensearchservice-domain-encryptionatrestoptions-kmskeyid

**Comment by TheDanBlanco** [comment]
hey @Ruben-Sh! i was able to achieve this with the following snippet:

```
EncryptionAtRestOptions:
  Enabled: True
  KmsKeyId: alias/aws/es
```

this matches what happens if you create an open search domain using the console settings listed above. this account did not have any aws managed keys previous to this creation. i am marking this issue as closed. if you need more help or this does not solve your issue, please feel free to reach back out and re-open!
