### ISSUE TITLE
In AWS::B2BI::Transformer, the status is created as 'inactive' even though the status is created as 'active'.

### ISSUE THREAD

**Issue by yushikato0131** [aws-cloudformation/cloudformation-coverage-roadmap#1878]
### Name of the resource

AWS::B2BI::Transformer

### Resource Name

AWS::B2BI::Transformer

### Issue Description

In AWS::B2BI::Transformer, the status is created as 'inactive' even though the status is created as 'active'.

This causes the error "Transformer status must be 'active'" in AWS::B2BI::Capability.

The resource is not added in the list of Name of the resource.

### Expected Behavior

As stated in the Issue Description

### Observed Behavior

As stated in the Issue Description

### Test Cases

As stated in the Issue Description

**Comment by aesgcm** [comment]
I think there is a typo in the name of the resource.  It says AWS::ACMPCA::Certificate but the resource mentioned in the ticket body is AWS::B2BI::Transformer

**Comment by yushikato0131** [comment]
> I think there is a typo in the name of the resource. It says AWS::ACMPCA::Certificate but the resource mentioned in the ticket body is AWS::B2BI::Transformer

hi aesgcm.
This is due to the fact that AWS::B2BI::Transformer was not present in the drop-down list at the time this issue was filed.

**Comment by yushikato0131** [comment]
Edited to AWS::ACMPCA::Certificate=>AWS::B2BI::Transformer

**Comment by dmoini** [comment]
At this moment, this is currently by design. An `AWS::B2BI::Transformer` is created in an inactive state by default and must be updated to an active state in a separate action. However, we realize that this is not a good customer experience for customers trying to create B2BI CloudFormation resources. We are discussing this concern internally.

In the meantime, can you pease recreate this issue in the [aws-cloudformation-resource-providers-b2bi GitHub repository](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-b2bi) so we can better track the issue?

**Comment by yushikato0131** [comment]
Hi dmoin.
Thank you. I have created a new Issue here.
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-b2bi/issues/21

**Comment by dmoini** [comment]
Issue has been addressed [here](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-b2bi/issues/21). This issue can now be closed.

**Comment by yushikato0131** [comment]
thank you dmoini!!
