### ISSUE TITLE
SAML Cognito Identity Provider: Signing and encryption settings

### ISSUE THREAD

**Issue by ryanolee** [aws-cloudformation/cloudformation-coverage-roadmap#1963]
### Name of the resource

AWS::Cognito::UserPoolIdentityProvider

### Description

The here are no setting for configuring Saml Signing and Encryption setting from cloudformation when creating a provider. 
![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/17767073/c9a245dd-6b30-4ee5-9d63-0e3fd4989467)
^ These are the settings that would ideally have parallel attributes in Cloud-formation in some capacity to configure.

Looking under https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolidentityprovider.html#aws-resource-cognito-userpoolidentityprovider--examples--Creating_a_new_SAML_identity_provider
There does not seem to be any "ProviderDetails" options for configuring these new options. Ideally it would be great to have the option to enable them when creating the provider!

**Comment by ryanolee** [comment]
As a follow up looks like this is more a documentation issue. Deploying with the following seems to work. Just not documented _anywhere_ in the CF or SDK documentation.
```
"ProviderDetails": {
     "IDPSignout": false,
     "MetadataURL": "xxx",
     "EncryptedResponses": "true",
     "RequestSigningAlgorithm": "rsa-sha256"
    }
```

**Comment by jrempel-aws** [comment]
It seems there was an issue with an outdated version of the documentation being published, and since has been resolved.

See:
- https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateIdentityProvider.html#CognitoUserPools-CreateIdentityProvider-request-ProviderDetails
- https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateIdentityProvider.html#CognitoUserPools-UpdateIdentityProvider-request-ProviderDetails
- https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_IdentityProviderType.html#CognitoUserPools-Type-IdentityProviderType-ProviderDetails
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolidentityprovider.html#cfn-cognito-userpoolidentityprovider-providerdetails

If there's anything we missed, feel free to file a ticket or re-open the issue.

**Comment by ryanolee** [comment]
Thanks for getting back. Looks to be all resolved  now. Thanks for updating  the docs!
