### ISSUE TITLE
AWS::EC2::KeyPair - can create resource via API, but not via CloudFormation

### ISSUE THREAD

**Issue by netroy** [aws-cloudformation/cloudformation-coverage-roadmap#335]
Customers who'd like to manage their SSH keys as a part of their stack, would like to have support for a `AWS::EC2::KeyPair` resource type.

Currently, there are a few [custom-resource implementation](https://github.com/dweomer/aws-cloudformation-keypair) for this. 
But, official support from Cloudformation would be much better.

Category: Compute, Security

**Comment by tvb** [comment]
I think automatically adding the key to SSM Parameter Store natively by CloudFormation would be the best solution.

**Comment by pnarve-aws** [comment]
Thank you for raising this request! We will be tracking this as part of EC2 Key Pairs roadmap. We would love to learn more about your use case. If you have a TAM/SA associated with the account, please reach out to them as well.

**Comment by rhbecker** [comment]
I just noticed that the [AWS::EC2::KeyPair](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-keypair.html) resource type seems to have been added on April 28, 2022, per the [CFN release history](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html).

I haven't tried using it yet, but presumably this issue is close-able?
