### ISSUE TITLE
AWS::SNS::Subscription - [BUG] RawMessageDelivery evaluated incorrectly on SNS email protocol

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/cloudformation-coverage-roadmap#399]
## Scope

For an [`AWS::SNS::Subscription`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html), CloudFormation is apparently only checking that the `RawMessageDelivery` attribute is present and ignoring the value, causing a stack creation error if the value is set to `false`.

## Expected behavior

For the value of `false`, the `RawMessageDelivery` attribute should be ignored.

## Category

Integration (SNS)

## Notes

Probably the same for `AWS::SNS::Topic`'s Subscriptions property.

Originally reported: https://github.com/iann0036/former2/issues/71

**Comment by shih** [comment]
Property `RawMessageDelivery` is not supported for `email` protocol, as this param is only supported for Firehose, SQS, HTTP/S endpoints. The errors got when creating stacks were thrown from SNS service instead of CloudFormation.

We don't do special value conversion for `RawMessageDelivery` for different endpoints, if you set this value as `false` for email endpoints, it is fail.
