### ISSUE TITLE
AWS::KinesisAnalyticsV2::Application - VpcConfiguration

### ISSUE THREAD

**Issue by grvhi** [aws-cloudformation/cloudformation-coverage-roadmap#547]
## 2. Scope of request 
Add support for VPC configuration for Kinesis Data Analytics for Java applications. VPC configurations can be set via the API, but not CloudFormation.

See: https://docs.aws.amazon.com/kinesisanalytics/latest/apiv2/API_VpcConfiguration.html

## 6. Category: 
Analytics

**Comment by sharp-pixel** [comment]
This is very important for well-architected solutions, and also a pre-requisite for implementation in CDK,

**Comment by kurtostfeld** [comment]
We are trying to configure a Kinesis Analytics app via CDK, and this issue is a problem for us. FYI, you can see the directly missing VpcConfigurations element on the CloudFormation docs:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalyticsv2-application-applicationconfiguration.html
https://docs.aws.amazon.com/kinesisanalytics/latest/apiv2/API_CreateApplication.html

**Comment by sunil-morya** [comment]
This feature request is very much required for my project, because for Attaching to Private Subnet in a VPC requires to login from console ( so you must have to be the user on that particular account where KDA is launched ) . user from tooling and development account can not configure it.

I request to please address this feature requirement on urgent basis.   It breaks our account strategy for Role Based access for our customer.
