### ISSUE TITLE
AWS::AppConfig::Deployment - property configurationVersion should be optional

### ISSUE THREAD

**Issue by RikJansen81** [aws-cloudformation/cloudformation-coverage-roadmap#641]
## 1. Title 
AWS::AppConfig::Deployment-property configurationVersion should be optional

## 2. Scope of request 
According to [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deployment.html) the configurationVersion should be optional, but it isn't.

## 3. Expected behavior

Cloudformation should accept a AWS::AppConfig::Deployment template without configurationVersion and use the latest version.

## 6. Category
Systems Manager (AppConfig)

**Comment by dggorsen** [comment]
Thanks for the suggestion RikJansen81! After taking a look at the AppConfig CloudFormation [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-deployment.html), it does appear that ConfigurationVersion is correctly marked as required. This is the desired behavior of the resource since users must specify which version of their configuration they would like to be deployed.

Hope this helps!

Best,
Dillon
