### ISSUE TITLE
AWS::Redshift::Cluster - Add support for stack level tags to AWS::Redshift::Cluster

### ISSUE THREAD

**Issue by badaldavda8** [aws-cloudformation/cloudformation-coverage-roadmap#644]
Add support for stack level tags to AWS::Redshift::Cluster

**Comment by shwetayakkali** [comment]
stack level tags support is available.

**Comment by ascar01973** [comment]
> stack level tags support is available.

Hello, @shwetayakkali.  Can you please clarify how this issue was resolved?  
Either I misunderstood the OP issue, or there is some step that I as a customer need to take, or the issue is not resolved.
Today, I created a redshift::Cluster via cloudformation and the stack-level tags did not automatically propagate to the Cluster, as is expected (and as occurs, e.g., with, RDS::DBCluster).  Please advise.  Thanks!

@badaldavda8, did I misunderstand your issue?

**Comment by ascar01973** [comment]
I was directed to this ticket by AWS Support when I opened Case 8791780291 on 27 august 2021. (Subject: "Chat: Stack-level tags are not propagated to stack resource Redshift::Cluster").  That case was closed because THIS issue (644) was open.  If this issue is truly resolved, then it seems I would need to re-open that case.  Please advise.  Thanks!

**Comment by adobe-sid** [comment]
Hello team,

looks like the Issue still exists.

I replicated and observed that resource level tags gets added to Cluster, can confirm it from the Redshift Console.
Stack level tags aren't applied to the Cluster.
Can we please have this issue resolved? 

Thanks!
