### ISSUE TITLE
AWS::StepFunctions::StateMachine - StateMachineType Changing StateMachineType should result in Replacement?

### ISSUE THREAD

**Issue by rogerchi** [aws-cloudformation/cloudformation-coverage-roadmap#671]
## 1. Title 
AWS::StepFunctions::StateMachine-StateMachineType

## 2. Scope of request 
AWS::StepFunctions::StateMachine-StateMachineType allows you to specify STANDARD or EXPRESS, but the documentation states that "You cannot update the type of a state machine once it has been created."  The Update requires is then set to "No interruption" (because updating this does nothing).

## 3. Expected behavior
Should this instead be Update requires: Replacement if the parameter is switched between STANDARD and EXPRESS?

## 4. Suggest specific test cases
Create a stack with a State Machine where type is STANDARD or EXPRESS.
Create change set where type is set to the other type.
State machine destroyed and replaced with a new state machine with the correct type

## 5. Helpful Links to speed up research and evaluation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-statemachinetype

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
Integration (MQ, SQS, SNS,...)
Integration (Step Functions)

**Comment by jormello** [comment]
Thanks for bringing this to our attention, we've merged a [PR](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-stepfunctions/pull/31) that will cause updates to the `StateMachineType` to result in resource replacement. The [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html) will be updated to reflect these changes.

**Comment by benbridts** [comment]
@jormello Is there any ETA for when this will be rolled out? It is a bit strange that this is closed while the actual behaviour is still to silently ignore changes to the `StateMachineType` property

**Comment by jormello** [comment]
Thanks for following up on this @benbridts . There were a few PRs merged around the same time. One of those PRs, which [addressed schema validation warnings](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-stepfunctions/pull/29), resulted in a new set of contract tests being run against the `AWS::StepFunctions::StateMachine` resource. These new contract tests were failing and blocked us from being able to deploy the fix for `StateMachineType`. 

We've since addressed the failing contract tests and expect the `StateMachineType` change to be available in all regions by end of week.

**Comment by jormello** [comment]
The change has been fully deployed and is available in all regions! Please let me know if there are any further concerns related to this.
