### ISSUE TITLE
AWS::RDS::DBInstance should not fail delete if the database is not found

### ISSUE THREAD

**Issue by lwoggardner** [aws-cloudformation/cloudformation-coverage-roadmap#679]
## 2. Scope of request 
DELETE of AWS::RDS::DBInstance resource

## 3. Expected behavior
DELETE of AWS::RDS::DBInstance resource that no longer exists should succeed

## 4. Suggest specific test cases
Manually delete a db from RDS console, then try delete via Cloudformation,  should succeed.

## 7. Additional context
If DBinstance is very large and DeletePolicy is "Snapshot" then cloudformation times out on first DELETE waiting for the snapshot to complete, RDS goes on to delete the DB.   I can live with that.

However, a subsequent attempt to delete the stack goes to DELETE_FAILED state because the DBInstance does not exist. 

Delete with "Retain" option will work, but is difficult to automate.

**Comment by moataz-mhmd** [comment]
By design, CloudFormation forces all its resource via [Contract Tests](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/contract-tests.html) to throw `NotExistException` if resource being deleted is not there. 

> Contract Tests runs every time we register new version of resource implementation. If failed, New version will not be registered and latest success version will stay in use.

However, I believe this is a legitimate request that will save CFN users manual work/scripting for deleting resources. This could be a feature on CFN level for all resources.
I opened two feature requests to CFN:
1. General request of auto Import resource if already exist, So no need to delete resource in first place as cleaning step to create it again: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1402. 
2. https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1403
