### ISSUE TITLE
AWS::ECS::Service - Properties-DeploymentConfiguration-deploymentCircuitBreaker

### ISSUE THREAD

**Issue by airmonitor** [aws-cloudformation/cloudformation-coverage-roadmap#724]
## 1. Title 
AWS::ECS::Service-Properties-DeploymentConfiguration-deploymentCircuitBreaker

## 2. Scope of request 
Please implement the deploymentCircuitBreaker configuration

## 3. Expected behavior
The CloudFormation service parses the request correctly and modifies the ECS service accordingly.

## 5. Helpful Links to speed up research and evaluation

Samples:
#### The AWS Blog post about enabling circuit breaker via CLI

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-ecs.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

1. Compute (EC2, ECS, EKS, Lambda...)

**Comment by pgarbe** [comment]
It's stated in the [release notes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html):
> AWS::ECS::Service
>    Use the DeploymentCircuitBreaker property to enable the deployment circuit breaker for a service.

But it seems that the docs haven't been updated.

**Comment by allenk3** [comment]
Looks like [docs have been updated](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentconfiguration.html)

**Comment by airmonitor** [comment]
After docs are updated can we have this please added to CDK?
Looking at the latest cdk 1.80.0, especially in class FargateService there is no deployment_configuration :/

**Comment by benbridts** [comment]
@airmonitor the next CDK should get this automatically because it's part of the [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) now.

I don't know if this needs a new release of the CDK, but if it does, [you can use one of these methods to work around the missing support until then](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html)

For additional CDK issues, you probably should open an [issue in their project](https://github.com/aws/aws-cdk)

**Comment by kenilshah27** [comment]
This changes are already deployed and are part of CFN and CDK. Since the issue was raised 8 months back i am assuming you are able to use the deploymentCircuitBreaker field in CDK and have not faced any issues since then.
