### ISSUE TITLE
CloudFormation: Delete Failed resource in the CleanUp stage becomes orphan after three attempts.

### ISSUE THREAD

**Issue by kiran-banisetti-tm-zz** [aws-cloudformation/cloudformation-coverage-roadmap#744]
If deletion process failed in the UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state, the CFN stack will not re-try the deletion and it simply gives the error warning as shown below:

Update successful. One or more resources could not be deleted.

However, the resource becomes orphan after this and can not be deleted from the CloudFormation.
We need to manually delete the remained resource from the AWS Console.
It is expected that, the resource should not get orphaned and the complete lifecycle should be handled by the CloudFormation even if the Delete failed in CleanUp stage.

I am suspecting this is a possible bug and needs to be addressed. If yes, please take it as a Feature request.

Reference 
1. https://medium.com/pablo-perez/cloudformation-cleanup-process-3b2aba70599

**Comment by CCludts** [comment]
We have seen the same issue (200+ resources failed to delete). I would like to add that we would already be satisfied if Cloudformation would have a 'Retry Failed Deletes' option that has to be manually invoked after the stack finished to update

**Comment by colliwhopper** [comment]
Same issue here.

**Comment by jimduden6804** [comment]
This is also a Problem for us

**Comment by tdmalone** [comment]
When this happens the stack still goes into UPDATE_COMPLETE, which is incorrect: the stack update _shouldn't_ succeed if a resource deletion fails. Otherwise there is no obvious way to surface this error - without perusing the Events tab (and/or checking the relevant service's API for delete success) every time one is deleting a resource. This can contribute to unexpected costs.

**Comment by TheDanBlanco** [comment]
hey, just confirming here - this is expected behavior. we surface a `DELETE_FAILED` event in the events in case cloudformation fails to delete a resource before entering a terminal state. we recommend auditing the events tab after a deployment to validate that resources aren't missed.

i've made sure the team is aware of this github issue in the meantime.
