### ISSUE TITLE
AWS::ServiceCatalog::PortfolioShare AccountId Property leading with "0" failes (does not match pattern {^[0-9]{12}$})

### ISSUE THREAD

**Issue by sysopcorner** [aws-cloudformation/cloudformation-coverage-roadmap#745]
Quick Summary:
1. AWS::ServiceCatalog::PortfolioShare - AccountId Property
2. Scope of request -> AWS::ServiceCatalog::PortfolioShare AccountId Property does not support AWS account IDs beginning with "0".  Deploying that resource results in error: `Property validation failure: [Value for property {/AccountId} does not match pattern {^[0-9]{12}$}]`
3. Expected behavior -> AccountId Property accepts AWS accounts with leading with "0"

**Comment by benbridts** [comment]
@sysopcorner Are you using a yaml template?

YAML will by default read numbers starting with a 0 as a base-8 number.
Which means that for eg.  account id `012345670123` (12 characters), CloudFormation will see `1402433619` (10 characters).

The solution is to (always) specify account ids as strings:

```
AccountId: "012345670123"
```
instead of 
```
AccountId: 012345670123  # this will be read as the number 1402433619
```
