### ISSUE TITLE
AWS::DMS::ReplicationTask failure when updating TableMappings

### ISSUE THREAD

**Issue by mdipirro** [aws-cloudformation/cloudformation-coverage-roadmap#753]
## 3. Issue
After the creation of an AWS::DMS::ReplicationTask we tried to modify the table mappings by adding one rule from the CloudFormation template we used to create the resource in the first place. The `dfif` shows that the previous rules will be deleted and replaced with a new set of rules containing the one we're trying to add. No other changes are shown.

However, the stack update fails with the following error:
```
Invalid task settings JSON (Service: AWSDatabaseMigrationService; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 8b1b6225-cda6-4896-be29-104da55e41d8; Proxy: null)
``` 

## 4. Steps to reproduce (numbered)
1. Create a DMB replication task via 

CloudFormation with a given set of table mappings and wait for it to be Ready. The rules are in the following form:
```
{
    "rules": [
        {
            "rule-type": "selection",
            "rule-id": "1",
            "rule-name": "1",
            "object-locator": {
                "schema-name": "appdb",
                "table-name": "account_type_defaults"
            },
            "rule-action": "explicit"
        },
        ...
    ]
}
```
2. Add or remove a table mapping, such as the following one, from the JSON in the CloudFormation template.
3. Update the stack and get the error

Please find attached the CloudFormation template we're using. [stack-dms-replicationtasks.template.txt](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/files/5815477/stack-dms-replicationtasks.template.txt)

## 5. Category
Migration & Transfer

## 6. Additional context (optional)
The failure occurs independently of the type of the update (i.e. if we try to add or remove a mapping). We tried the following and confirm they are working fine:
* destroying the existing stack and re-creating it with the updated TableMappings (this, of course, destroys the existing AWS::DMS::ReplicationTask and creates another one;
* copying the JSON with the added mapping in the JSON editor for the table mappings in the AWS console. Doing so to remove the mapping also worked
* modifying the table mappings from the CLI after saving the JSON with the added mapping in a file:
```
aws dms modify-replication-task --replication-task-arn "arn:aws:dms:eu-central-1:245725305788:task:IBKIBUNVWCCP5DFJCISMT5REQBLLN5BQWS4PB3I" --table-mappings file://tables.json
```
* removing the `\n` from the JSON

**Comment by alberli-23** [comment]
Updating ReplicationTask through CloudFormation is not currently supported. When DMS creates a replication task, the ReplicationTaskSettings defined by the customer will be modified by appending default settings, causing a CloudFormation “drift” where the new setting is different from the original setting. Since DMS does not support drift detection, updating resources such as ReplicationTask cannot be done entirely through CloudFormation. To work around this issue, you could modify the ReplicationTaskSettings to reflect the actual configuration shown in the DMS console.

For more information about resources supporting drift detection, please refer to: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
