### ISSUE TITLE
AWS::RDS::DBInstance - Support for using "apply" parameter for RDS modify DB Instance call

### ISSUE THREAD

**Issue by vsriv8387** [aws-cloudformation/cloudformation-coverage-roadmap#762]
We are not able to change password from CloudFormation immediately. They have to wait for the maintenance window to get it done.

They want the changes to be reflected immediately.

**Comment by osdrv** [comment]
All CFN update requests to AWS::RDS::DBCluster are marked as `applyImmediately=true` now (ref: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/blob/master/aws-rds-dbcluster/src/main/java/software/amazon/rds/dbcluster/Translator.java#L196). @vsriv8387 I understand it's been while since you opened the ticket. Could you please confirm you are no longer experiencing this delay in your workloads? Thank you.
