### ISSUE TITLE
AWS::MediaConnect::Flow VPC Interface Support

### ISSUE THREAD

**Issue by kemra102** [aws-cloudformation/cloudformation-coverage-roadmap#764]
## 1. Title 
`AWS::MediaConnect::Flow` VPC Interface support

## 2. Scope of request 
Allow a VPC Interface to be created as a property of the `AWS::MediaConnect::Flow` resource.

The current design of creating a VPC Interface separately via the `AWS::MediaConnect::FlowVpcInterface` has a ciruclar dependency issue as when creating a `AWS::MediaConnect::Flow` resource you must specify either the `EntitlementArn`, `VpcInterfaceName` or `WhitelistCidr` (as sub properties of the `Source` property). How ever `AWS::MediaConnect::FlowVpcInterface` requires the `FlowArn` property. As such it creates a circular dependency.

The only work around right now is to create the `AWS::MediaConnect::Flow` with a `WhitelistCidr` then update the CF template with the `AWS::MediaConnect::FlowVpcInterface` resource and update the `AWS::MediaConnect::Flow` with the `VpcInterfaceName` instead of a `WhitelistCidr`.

For some of us this doesn't work as if we are using tools such as Terraform to orchestrate we would create a module that we would re-use to create EMX Flow resources. Obviously in this situation a 2 step solution does not work.

As such it would be ideal if the `AWS::MediaConnect::Flow` resource had a `VpcInterface` property (with incidentally the AWS API allows) so that the resource(s) were created at the same time and we side step the circular dependency issues.

## 3. Expected behavior

It would be ideal if the `AWS::MediaConnect::Flow` resource had a `VpcInterface` property (with incidentally the AWS API allows) so that the resource(s) were created at the same time and we side step the circular dependency issues.

## 4. Suggest specific test cases

Test the creation of `AWS::MediaConnect::Flow` resources with VPC Interfaces.

## 5. Helpful Links to speed up research and evaluation

- https://docs.aws.amazon.com/mediaconnect/latest/api/v1-flows.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

Media Services

**Comment by adam-kliczek** [comment]
Hi. I'm really happy somebody raised this issue. We use a few hundreds of MediaConnects and these additional steps required to create or delete EMXes with VPC Interfaces are quite annoying. This request was raised almost 3 years ago - is there any update on when the feature will be shipped? Thanks.

**Comment by ciriolie** [comment]
Hello. The MediaConnect team has launched improved support for VPC interfaces using CloudFormation that should resolve this circular dependency issue. VPC interfaces can now be defined as part of an `AWS::MediaConnect::Flow` either during create or update, rather than as a separate `AWS::MediaConnect::FlowVpcInterface` resource. Defining VPC interfaces in this way removes the need to update the `AWS::MediaConnect::Flow` to add them successfully. We appreciate your patience as we resolved this issue. More details about the new functionality can be found in the MediaConnect CloudFormation documentation. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediaconnect-flow.html

**Comment by adam-kliczek** [comment]
Finally! Thanks. :)

**Comment by MGSAWS** [comment]
@aleeaa-aws
