### ISSUE TITLE
AWS::Forecast

### ISSUE THREAD

**Issue by somiron** [aws-cloudformation/cloudformation-coverage-roadmap#770]
2. Scope of request -> new service support is desired
3. Expected behavior -> Ability to manage Amazon Forecast resources through CloudFormation
4. Test case recommendation (optional) -> NA
5. Links to existing API doc (optional) -> NA
6. Category tag (optional) -> 6. Machine Learning
7. Any additional context (optional) -> NA

**Comment by Jimin980921** [comment]
Hello, I have some questions about aws forecast.
1. In the attached photo, if num_averaged_models=3, it means the average of the three models. What model do you mean? Are you referring to a model like arima?

2. Does context_length mean train data length? If not, what length are you talking about?

3. If max_learning_rate_decays is 0, is learning_rate_decay meaningless?
![그림1](https://user-images.githubusercontent.com/57060127/113541284-db741280-961c-11eb-8e0b-860214cc195f.png)

**Comment by benbridts** [comment]
@Jimin980921 This repository is meant for missing Resources/Services that are missing (some) CloudFormation support, not for general questions about the service, For service-related support, you can look in the [AWS Documentation](https://aws.amazon.com/documentation/), visit the [AWS Discussion Forums](https://forums.aws.amazon.com/index.jspa), or use the [AWS Support Center](https://console.aws.amazon.com/support/home#/). Of course, there are also third-party places, like StackOverflow,  AWS-related Slack and Discord communities, and Reddit.

----------

However, since we're here anyway; here are some more concrete pointers (but I recommend one of the above places for more questions/comments).

From the parameters in the screenshot, it looks like you're using the DeepAR+ algorithm. A more in-depth explanation of the training parameters can be found in the [Forecast Documentation](https://docs.aws.amazon.com/forecast/latest/dg/aws-forecast-recipe-deeparplus.html). If that's not the one you're using, there is also [a more generic overview page](https://docs.aws.amazon.com/forecast/latest/dg/aws-forecast-choosing-recipes.html).

**Comment by TheDanBlanco** [comment]
there are some [resources](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Forecast.html), but i'm not well-versed in forecast. if these aren't sufficient, please re-open this issue with some more information on what's required. thanks!
