### ISSUE TITLE
AWS::Cognito::UserPoolUICustomizationAttachment - add ImageData property

### ISSUE THREAD

**Issue by rnhurt** [aws-cloudformation/cloudformation-coverage-roadmap#797]
## 1. Title 
AWS::Cognito::UserPoolUICustomizationAttachment

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
8. Security (IAM, KMS...)

**Comment by nsorens** [comment]
The API takes in a blob of image data, but I'd imagine this is not supported in CFN / JSON for size or encoding reasons.

**Comment by rnhurt** [comment]
Ok, this says that it's Shipped but I checked the docs and they still say: 
```
Setting a logo image isn't supported from AWS CloudFormation. Use 
the Amazon Cognito SetUICustomization API operation to set the image.
```
Is there a time frame where this feature is released?

**Comment by ekadas** [comment]
I'd also be interested in knowing the status. The bot marked it as **Shipped**, however using `ImageFile` is not documented and does not pass validation on CloudFormation. Currently, in order to prevent new CloudFormation deployments unsetting logos, one would need to implement custom resource, which is not ideal.
