### ISSUE TITLE
AWS::Lambda::Function - Code-ZipFile

### ISSUE THREAD

**Issue by rclark** [aws-cloudformation/cloudformation-coverage-roadmap#80]
## 2. Scope of request

Support for function code via `ZipFile` in Lambda functions with any node.js/python runtime

## 3. Expected behavior

I should be able to use the `ZipFile` attribute for any node.js/python runtime I choose

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Compute

**Comment by kalrish** [comment]
Please consider Ruby as well.

**Comment by scliffo** [comment]
Node.js 8.10 reaches EOL on 31 Dec 2019.
What is the ETA for ZipFile support with Node.js 10.x runtime?

**Comment by oussemos** [comment]
+1

**Comment by benkehoe** [comment]
@oussemos, it's generally better GitHub etiquette to use reactions rather than "+1" comments, which create clutter and generate notifications. It's the "+😀" button on the header bar for a comment. You can also click an existing reaction to add to it.
See also: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/

**Comment by nija-at** [comment]
Can we know what the status of this issue is? 

With NodeJS8 being deprecated, this feature is crucial for customers to upgrade their Lambda function to Node10 when they are using inline code in their CloudFormation template.

**Comment by benkehoe** [comment]
![image](https://user-images.githubusercontent.com/1650723/68795228-88ac4c00-061e-11ea-9901-150bc3cbda22.png)

**Comment by nija-at** [comment]
Correcting myself - tried this out myself and it seems that CloudFormation now supports inline code for Nodejs10.

**Comment by arnulfojr** [comment]
I had faced this issue but for node12.x any updates on support for node12.x?

**Comment by monken** [comment]
Guess it's Groundhog Day. Both python3.8 and nodejs12.x are not supported by CloudFormation inline functions. How about a more fundamental fix? Why is this parameter even typed? Let the Lambda API return an error if the desired runtime is not available.

**Comment by luiseduardocolon** [comment]
Zipfile support for nodejs10.x is deployed and completed. Also, nodejs12.x work is completed and docs will be available soon.

**Comment by monken** [comment]
@luiseduardocolon Thank you!!

**Comment by direvus** [comment]
Still no support for inline code with python3.8.

**Comment by luiseduardocolon** [comment]
Moving from shipped to working on it, because of python 3.8 support not quite being there yet.

**Comment by kylelaker** [comment]
Will the Python 3.8 support result in a change to the [`cfnresponse`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html#w2ab1c19c25c14b9c15) module since the version of `botocore` in the Python 3.8 Lambda runtime no longer has the vendored `requests` module?

**Comment by PatMyron** [comment]
> Guess it's Groundhog Day. Both python3.8 and nodejs12.x are not supported by CloudFormation inline functions. How about a more fundamental fix? Why is this parameter even typed? Let the Lambda API return an error if the desired runtime is not available.

[This is key](https://code.amazon.com/r/CR-19374663). [`ZipFile`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile) is currently restricted to Lambda Runtimes with [`cfn-response`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html) support. While there may be more work for [`cfn-response`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html) support, that restriction should be removed because [`ZipFile`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile) support is still useful without [`cfn-response`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html) support

**Comment by takeda** [comment]
Any update on enabling `ZipFile` for python3.8?

**Comment by nico-oculusd** [comment]
Bump: Any update on enabling `ZipFile` for python3.8?

**Comment by tjstansell** [comment]
@PatMyron  According to https://github.com/awslabs/aws-cloudformation-templates/commit/44b76a1f694f82eeee14fe804bf9dc973fdc2230#diff-c5c12db01c1b4f18f951451d08e7828f, cfnresponse has not depended on the requests library since April 29, 2020... there should be nothing blocking adding python3.8 support in ZipFile.  Can anyone here comment on a timeline for this?

**Comment by luiseduardocolon** [comment]
Hello there.  Just wanted to let you know that we expect to release this soon, hopefully in the coming days, barring any last-minute regression.

**Comment by bchew** [comment]
@luiseduardocolon I've just tried to deploy using `ZipFile` with `nodejs14.x`, have gotten the failure back from CloudFormation: `ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x, python2.7, python3.6, python3.7, python3.8.`

**Comment by anirudhsaligram** [comment]
I see the same issue as @bchew here.

**Comment by jensrutschmann** [comment]
@luiseduardocolon `nodejs14.x` is still not available for use with `ZipFile`. That's quite annoying because node 14 is the [current LTS](https://nodejs.org/en/about/releases) and because it's unavailable I need to migrate from node 10 to 12 now (when it's already known that node 16 will be the next LTS later this year). Wish I could upgrade to 16.
Any news when at least node 14 will be available for `ZipFile`?

**Comment by brianterry** [comment]
@jensrutschmann , `nodejs14.x` is now supported. 

Please review the docs at:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

**Comment by yerzhan7** [comment]
I have just tried to deploy to `eu-west-1` region and still got error:

```
Resource handler returned message: "Invalid request provided: The ZipFile attribute is not supported for the runtime 'nodejs14.x'" (RequestToken: 5be7b547-9896-877d-b30f-7fd299b22b32, HandlerErrorCode: InvalidRequest)
```

Please re-open the issue, thanks.

**Comment by danilobuerger** [comment]
@yerzhan7 @brianterry For me it worked just fine on us-east-1. Maybe its not deployed to every region yet?

**Comment by brianterry** [comment]
Thanks, @danilobuerger. We are researching.

**Comment by bchew** [comment]
I've just tested redeploying the same stack which failed back in February per previous comment, worked fine in `us-west-2` region. Thanks @brianterry!

**Comment by ChrisPearce** [comment]
Unfortunately it is not working in eu-west-2

**Comment by Canuteson** [comment]
Still currently failing to deploy to us-east-1 with Node 14:
Resource handler returned message: "Invalid request provided: The ZipFile attribute is not supported for the runtime 'nodejs14.x'"

**Comment by hoangenouvo** [comment]
same error with @Canuteson

**Comment by ChrisPearce** [comment]
Another point to note is that the change is not yet included in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by dotcypress** [comment]
> Still currently failing to deploy to us-east-1 with Node 14:
> Resource handler returned message: "Invalid request provided: The ZipFile attribute is not supported for the runtime 'nodejs14.x'".
> 
> Mine are also Edge Functions.

Same issue on `us-east-1`

**Comment by VincentvdE** [comment]
Same issue on `eu-central-1`

**Comment by imjustd** [comment]
Node v14.x not working for `us-east-1` had to revert to Node v12.x

**Comment by ChrisPearce** [comment]
With NodeJS *16* then due to reach LTS on 26 Oct 2021, is there also a plan for that to then be supported as well?

**Comment by tlindsay42** [comment]
Same issue in us-west-2. Reverting to Node.js 12.x worked.

**Comment by EBeureux** [comment]
Issue still exists with nodejs14.x as of today on eu-west-3...

**Comment by heikkima** [comment]
I received error `The ZipFile attribute is not supported for the runtime 'nodejs14.x'"` when I tried to deploy a new edge lambda to us-east-1 region.

I was able to first deploy the same lambda as 'nodejs12.x' and after the CloudFormation stack was in 'COMPLETE' state I updated the lambda to nodejs14.x. 

It's a temporary work-around but I hope it's helpful for others.

**Comment by chipironcin** [comment]
Happening in eu-west-1 too 😢 
I would prefer not run my code with Node12.x

**Comment by imjustd** [comment]
History repeats with every new Node.js AWS Lambda runtime https://forums.aws.amazon.com/thread.jspa?threadID=303166

**Comment by paulsnappet** [comment]
It seems to be a per-account thing for me! Deploying to eu-west-1 in account A works fine, but deploying to same region in Account B gives the dreaded `The ZipFile attribute is not supported for the runtime 'nodejs14.x'"` message.

**Comment by abdennour** [comment]
happen in us-east-1 while deploying lambda edge thru cfn.
quick release of the revert will be helpful

**Comment by imjustd** [comment]
Is this fixed already? We're almost August and Node.js v16 will get into LTS active status in October https://nodejs.org/en/about/releases/ so suppose this will be the new Node.js version in AWS Lambda shortly.
I really think Amazon should make this `ZipFile` support automatic when a new Node.js version gets implemented into AWS Lambda. Don't get why we need to wait years before this works. Does it really need custom development for each version?

**Comment by hortondust** [comment]
I was able to deploy a ZipFile with node 14.x in us-west-2 today

**Comment by imjustd** [comment]
Finally, this works! Just tested with Node.js v14.x in `us-east-1` all my Lambdas successfully deployed with the `InlineCode` directive in the SAM template definition file.

**Comment by ChrisPearce** [comment]
It is now working for eu-west-2

**Comment by vileppanen** [comment]
Bumping up --> I'm getting the ZipFile unsupported error in eu-west-1 in my own account, for both node12 and node14.

Is there any written analysis somewhere on what is causing the issue?

**Comment by michaelbrewer** [comment]
is Python3.9 now also supported

**Comment by micahduron** [comment]
@michaelbrewer Yes, you can now inline python3.9 code using ZipFile.

We introduced a change that enables the use of the ZipFile property with all nodejs and python runtimes, so newly released versions of these runtimes will have day-one support for inlined code.
