### ISSUE TITLE
AWS::RDS::DBInstance - BUG? RDS Modifying immediately after import

### ISSUE THREAD

**Issue by jk2l** [aws-cloudformation/cloudformation-coverage-roadmap#809]
For Stack Resource import process, if I am not mistaken the import process only import the instance. and it is not suppose to modify it. And using CloudFormation drift detection after import to check anything misaligned 

At the moment, I just imported a AWS::RDS::DBInstance with gp2, but due to one missing field (StorageType). after import it immediately trying to convert it to Standard.

This did also caused unexpected operation

**Comment by moataz-mhmd** [comment]
This is expected behavior and covered in [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import.html)

> Verify that resources and their properties defined in the template match the intended configuration of the resource import to avoid unexpected changes.

As CFN user, this can be a good feature to implement which import resource without triggering update that will allow user to drift detect and compare resource with his stack. I opened request ti CFN platform here: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1497
