### ISSUE TITLE
AWS::WAFv2::WebACL RegexMatchStatement

### ISSUE THREAD

**Issue by barryhagan** [aws-cloudformation/cloudformation-coverage-roadmap#933]
### Name of the resource

AWS::WAFv2::WebACL

### Description

`RegexMatchStatement` is missing from the supported Statements for WAFv2 rules, but available in the corresponding API:

API: https://docs.aws.amazon.com/waf/latest/APIReference/API_RegexMatchStatement.html

CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-statement.html

You can probably work around this with `RegexPatternSet` but that seems unnecessary if you have a single regex to use and it will cost more in capacity to run a pattern set with one entry.

**Comment by danwashusen** [comment]
Trying to manage WAFv2 with Cloudformation has been an excruciating process of trial and error, to the point I'm amazed anyone actually uses it... 

After finally getting it to a point that it's not completely useless (which it is by default IMO, especially with the "WAF automations project") with the 'work-around' mentioned here on our staging environment, I find out that I can't deploy to production because each **ACCOUNT** is limited to 10 regex pattern sets...

AARG!!!!

**Comment by jasvinc** [comment]
This issue has been resolved.
WAF team has added `RegexMatchStatement` support for `AWS::WAFv2::WebACL` on cloud formation. 
Please refer : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-statement.html
