### ISSUE TITLE
AWS::EFS::MountTarget - CF not respecting dependency between ::LocationEFS and ::MountTargets

### ISSUE THREAD

**Issue by lancerall** [aws-cloudformation/cloudformation-coverage-roadmap#971]
### Name of the resource

AWS::EFS::MountTarget

### Resource Name

AWS::EFS::MountTarget

### Issue Description

CloudFormation does not appear to be respecting the dependency between DataSync::LocationEFS resources and EFS::MountTarget resources. In the event that a FileSystem, MountTargets, and DataSync::LocationEFS are deployed via CF, a race condition exists between the creation of the MountTargets and the LocationEFS. CF is waiting for the Filesystem to be created/updated before creating the LocationEFS, but it does not wait for MountTargets to exist. Stack create or update fails.

Steps to reproduce:
1. Deploy attached yaml CF template
2. Observe result

[myfs.yaml.zip](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/files/7488079/myfs.yaml.zip)

### Expected Behavior

CloudFormation waits for both the FileSystem and MountTargets to be created/updated before creating the LocationEFS

### Observed Behavior

CloudFormation only waits for creation of the FileSystem before creating/updating the LocationEFS...

Creation of the ::LocationEFS fails with this error:
Resource handler returned message: "Invalid request provided: No valid mount targets for EFS filesystem arn:aws:elasticfilesystem:us-east-1:111111111111:file-system/fs-aaaaaaaa found in subnet subnet-00000000000000000. Please provide a subnet that contains a mount target.

Stack rolls back / fails
<img width="1290" alt="Screen Shot 2021-11-05 at 1 04 33 PM" src="https://user-images.githubusercontent.com/3745410/140558061-8baa39b1-1522-4c56-a8ac-dc0443c2a5d3.png">
.

### Test Cases

Deploy the attached yaml CF template to attempt creating a Filesystem, Mount targets, and LocationEFS together (this will fail)
Deploy a template which includes a Filesystem and Mount targets, then update the stack where the updated template includes the addition of a LocationEFS resource (this will pass)
Deploy a template which includes a Filesystem and Mount targets, then update the stack where the updated template will replace the Filesystem, and will add a LocationEFS resource (this will fail)
Deploy the attached yaml CF template, comment in the DependsOn line for the EFSLocation resource (this will pass)

### Other Details

I can add DependsOn: [MountTargetA, MountTargetB] to my ::LocationEFS resource as a workaround.

**Comment by mitkonikolov** [comment]
Hi lancerall,

Thank you for reaching out to us. CloudFormation dependencies are used to control the order in which resources are created. They are specified explicitly via the `DependsOn` attribute or implicitly by referring to a resource in the definition of another one.

In the use case you shared the `LocationEFS` resource has an implicit dependency on the `FileSystem` resource. CloudFormation therefore waits for the `FileSystem` to become available before initiating the creation of the `LocationEFS`. The dependencies are not intended for any other validations on the state of the `FileSystem` resource like for example its properties or the state of related resources like its `MountTargets`, and since `LocationEFS` does not have a dependency on the `MountTargets`, it does not require waiting for their creation.

Customers have the opportunity to define the desired state of their resources as well as any non-implicit dependencies. In this case the dependency should be specified explicitly via the `DependsOn` attribute.

Sharing relevant [CFN documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html) with further information on CFN dependencies if that helps.

Mitko
